# Generated by Django 5.2.5 on 2025-12-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_admissionnote_admissionrequirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News title', max_length=200)),
                ('date', models.DateField(help_text='Publication date')),
                ('body', models.TextField(help_text='News content')),
                ('details', models.TextField(blank=True, help_text='Full details shown in modal; falls back to body if empty')),
                ('image', models.ImageField(blank=True, help_text='News image', null=True, upload_to='news/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['display_order', '-date', 'title'],
            },
        ),
    ]
