# Generated by Django 5.2.5 on 2025-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(help_text='Institution vision statement')),
                ('mission', models.TextField(help_text='Institution mission statement')),
                ('goals', models.TextField(help_text='Institution goals (one per line)')),
                ('core_values', models.TextField(help_text='Core values description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this information is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institutional Information',
                'verbose_name_plural': 'Institutional Information',
                'ordering': ['-updated_at'],
            },
        ),
    ]
