# Generated by Django 5.2.5 on 2025-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, help_text='Achievement image', null=True, upload_to='achievements/'),
        ),
    ]
