# Generated by Django 4.2.7 on 2025-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_achievement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentprocessstep',
            options={'ordering': ['category', 'display_order', 'step_number'], 'verbose_name': 'Enrollment Process Step', 'verbose_name_plural': 'Enrollment Process Steps'},
        ),
        migrations.AddField(
            model_name='enrollmentprocessstep',
            name='category',
            field=models.CharField(choices=[('new-scholar', 'New Student (Scholar)'), ('new-non-scholar', 'New Student (Non-Scholar)'), ('continuing-scholar', 'Continuing Student (Scholar)'), ('continuing-non-scholar', 'Continuing Student (Non-Scholar)')], default='new-scholar', help_text='Student category', max_length=30),
        ),
    ]
