"""
Django settings for ccb_portal_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_env_variable(var_name, default=None, required=False):
    """Get environment variable or return default/raise error"""
    value = os.getenv(var_name, default)
    if required and not value:
        raise ImproperlyConfigured(f"Required environment variable '{var_name}' is not set")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production, fallback to default for development
SECRET_KEY = get_env_variable(
    'DJANGO_SECRET_KEY',
    default='django-insecure-6epnt%znb*)x+vj1*&+r)f33dr(%i)bkdy(gc9fk@h%#+3c@3)'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable('DJANGO_DEBUG', 'True').lower() == 'true'

# Security: Restrict ALLOWED_HOSTS in production
if DEBUG:
    # In development, allow all hosts
    ALLOWED_HOSTS = ['*']
else:
    # In production, specify allowed hosts
    allowed_hosts_env = get_env_variable('ALLOWED_HOSTS', '*')
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()] if allowed_hosts_env else []
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production via environment variable")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'portal',
    'anymail',
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ccb_portal_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ccb_portal_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    # Local development - MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'ccb_portal',
            'USER': 'root',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '3306',
            'OPTIONS': {
                'charset': 'utf8mb4',
                'sql_mode': 'STRICT_TRANS_TABLES',
            },
        }
    }
else:
    # Production - PostgreSQL from Render
    DATABASES = {
        'default': dj_database_url.config(
            default=get_env_variable('DATABASE_URL', required=True),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'build',  # React build files
]

# Cloudinary Configuration
# NOTE: In production, this will be overridden by production_settings.py
# In development, we use local storage
# DO NOT call cloudinary.config() here - let production_settings.py handle it

cloudinary_url = os.getenv('CLOUDINARY_URL')
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': '',
    'API_KEY': '',
    'API_SECRET': '',
}

# Media files - Default to local storage in development
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default to local storage - production_settings.py will override if needed
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Production Media Configuration
# Serve media files in production (Render will handle this via nginx)
# But we need to ensure the URLs are properly constructed
if not DEBUG:
    # Ensure MEDIA_URL is absolute URL for production
    PUBLIC_MEDIA_URL = get_env_variable('PUBLIC_MEDIA_URL', f"{get_env_variable('PUBLIC_BASE_URL', '')}/media/")
    if PUBLIC_MEDIA_URL and not PUBLIC_MEDIA_URL.endswith('/'):
        PUBLIC_MEDIA_URL += '/'

# CORS settings
# Security: Restrict CORS in production
if DEBUG:
    # In development, allow all origins so mobile/tablet (LAN IP) can access the API
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # In production, specify allowed origins
    cors_origins_env = get_env_variable('CORS_ALLOWED_ORIGINS', '')
    if cors_origins_env:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
    else:
        CORS_ALLOWED_ORIGINS = [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "https://ccb-portal-static.onrender.com",  # Static frontend site
        ]
    # Additional CORS security settings
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
    ]

CORS_ALLOW_CREDENTIALS = True

# WhiteNoise settings
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Email settings via Anymail (Brevo)
# Security: Use environment variables for sensitive credentials
# Note: User requested to set the BREVO API key directly here.
BREVO_API_KEY = get_env_variable(
    "BREVO_API_KEY",
    "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"
)
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend" if BREVO_API_KEY else "django.core.mail.backends.console.EmailBackend"

if BREVO_API_KEY:
    try:
        import anymail  # noqa: F401
        ANYMAIL = {
            "BREVO_API_KEY": BREVO_API_KEY,
            # Enable to see full request/response details in console for troubleshooting (only in DEBUG)
            "DEBUG_API_REQUESTS": DEBUG and get_env_variable("ANYMAIL_DEBUG", "0") == "1",
        }
    except ImportError:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
        ANYMAIL = {}

# OpenAI API Key for Chatbot
# Set OPENAI_API_KEY environment variable or it will fallback to empty (chatbot will use rule-based responses)
OPENAI_API_KEY = get_env_variable("OPENAI_API_KEY", "")

# Fallback SMTP (optional) if Anymail not configured
if not BREVO_API_KEY:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = get_env_variable("EMAIL_HOST", "smtp-relay.brevo.com")
    EMAIL_PORT = int(get_env_variable("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = get_env_variable("EMAIL_USE_TLS", "True").lower() == "true"
    EMAIL_HOST_USER = get_env_variable("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = get_env_variable("EMAIL_HOST_PASSWORD", "abcdefghijklmnopqrstuvwxyz")

DEFAULT_FROM_EMAIL = get_env_variable("DEFAULT_FROM_EMAIL", "citycollegeofbayawan@gmail.com")
SERVER_EMAIL = get_env_variable("SERVER_EMAIL", DEFAULT_FROM_EMAIL)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL configuration
LOGIN_URL = '/admin/'  # Redirect to Django admin login
LOGIN_REDIRECT_URL = '/admin/'  # After login, redirect here

# Security Settings
if not DEBUG:
    # Security headers for production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = get_env_variable('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
else:
    # Less strict settings for development
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Additional security settings
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Database security (already using parameterized queries via Django ORM)
# Ensure no raw SQL queries without proper sanitization
DATABASES['default']['OPTIONS']['init_command'] = "SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO'"

# Cache configuration for security features (rate limiting, account lockout, audit logs)
# Using local memory cache for development, Redis/Memcached recommended for production
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        },
        'TIMEOUT': 3600,  # Default timeout: 1 hour
    }
}

# For production, use Redis or Memcached:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }
